# PostgreSQL + TimescaleDB + pgvector + 초기 벡터 테이블 생성
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
#      - /Users/seowon/dev/docker/postgres/pgdata:/var/lib/postgresql/data  # M:데이터 저장 경로
      - /c/dev/docker/postgres/pgdata:/var/lib/postgresql/data  # W:데이터 저장 경로
      - ./init:/docker-entrypoint-initdb.d/init.sql  # 초기 스크립트 자동 실행
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vectordb"]
      interval: 5s
      timeout: 3s
      retries: 5
