services:
  sil_maria:
    image: mariadb:10.6 # mariadb 버전
    container_name: sil_maria    # container 이름
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: maria
      MARIADB_DATABASE: maria
      MARIADB_USER: maria
      MARIADB_PASSWORD: maria
    volumes:
      - ./master_db/data:/var/lib/mysql   # 각종 log와 index등 volume이 저장되는 디렉토리
      - ./master_db/config/:/etc/mysql/conf.d   # 이전에 나왔던 ./master/config/my.cnf 를 써줌으로써 설정을 reference해준다
    ports:
      - "3306:3306"