services:
  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: no

volumes:
  redis-data: